name: CI

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]

jobs:
    lint-format-typecheck-build:
        name: Lint, Format, Typecheck & Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10.3.0

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check code formatting
              run: pnpm format:check

            - name: Create empty database file for build
              run: |
                  mkdir -p .data
                  touch .data/sqlite.db

            - name: Create mock .env file for build
              run: |
                  echo "DATABASE_URL=file:.data/sqlite.db" > .env.local
                  echo "OPENAI_API_KEY=dummy-key-for-ci" >> .env.local

            - name: Lint
              run: pnpm lint

            - name: Type check
              run: pnpm typecheck

            - name: Build
              run: pnpm build
